//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myshopify
{
    using System;
    using System.Collections.Generic;
    
    public partial class tiendas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tiendas()
        {
            this.ordenes = new HashSet<ordenes>();
        }
    
        public string tienda_id { get; set; }
        public string vchNombreTienda { get; set; }
        public string vchUrlOrdenes { get; set; }
        public string vchUrlTransacciones { get; set; }
        public string vchUsername { get; set; }
        public string vchPassword { get; set; }
        public bool bitActiva { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordenes> ordenes { get; set; }
    }
}
